# Site settings
title: "Alessia Vannini"
description: "Portfolio und Blogbeiträge"
author:
  name: "Alessia Vannini"

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

sass:
  style: compressed

# Dateien, die Jekyll NICHT in die fertige Seite kopieren soll
exclude:
  - README.md
  - README.txt
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
